[REF] Radarr CM

diff --git a/radarr/radarr-cm.yaml b/radarr/radarr-cm.yaml
--- a/radarr/radarr-cm.yaml
+++ b/radarr/radarr-cm.yaml
@@ -80,16 +80,7 @@ data:
             configMap:
               name: radarr-cm
               defaultMode: 0755
-  tarshot.sh: |
-    #!/bin/sh
-    set -e
-
-    export NAMESPACE='radarr'
-
-    log() {
-      echo "$(date +'%Y-%m-%d %H:%M:%S') - $1"
-    }
-
+  tarshot_delete_pvc.sh: |
     delete_pvc() {
       local pvc_name=$1
       local namespace=$2
@@ -104,6 +95,33 @@ data:
         log "PVC $pvc_name not found" &> /dev/null
       fi
     }
+
+  tarshot.sh: |
+    #!/bin/sh
+    set -e
+
+    export NAMESPACE='radarr'
+
+    log() {
+      echo "$(date +'%Y-%m-%d %H:%M:%S') - $1"
+    }
+
+    source /scripts/tarshot_delete_pvc.sh
+
+    # delete_pvc() {
+    #   local pvc_name=$1
+    #   local namespace=$2
+
+    #   if kubectl get pvc "$pvc_name" -n "$namespace" &> /dev/null; then
+    #     log "Removing finalizers from PVC"
+    #     kubectl patch pvc ${NAMESPACE}-pvc-tarshot -n ${NAMESPACE} --type=json -p '[{"op": "remove", "path": "/metadata/finalizers"}]' && log "Finalizers removed from PVC"
+    #     sleep 1
+    #     log "Deleting PVC $pvc_name"
+    #     kubectl delete pvc "$pvc_name" -n "$namespace" --ignore-not-found && log "PVC $pvc_name deleted"
+    #   else
+    #     log "PVC $pvc_name not found" &> /dev/null
+    #   fi
+    # }
 
     delete_volumesnapshot() {
       local volumesnapshot_name=$1
