[FIX] Radarr CM

diff --git a/radarr/radarr-cm.yaml b/radarr/radarr-cm.yaml
--- a/radarr/radarr-cm.yaml
+++ b/radarr/radarr-cm.yaml
@@ -123,7 +123,16 @@ data:
     kubectl delete job radarr-job-tarshot -n radarr --ignore-not-found && log "Job deleted"
     log "Deleting VolumeSnapshot"
     kubectl delete volumesnapshot radarr-volumesnapshot-tarshot -n radarr --ignore-not-found && log "VolumeSnapshot deleted"
+
+
     log "Deleting PVC"
-    kubectl delete pvc radarr-pvc-tarshot -n radarr --ignore-not-found && log "PVC deleted"
+    # kubectl delete pvc radarr-pvc-tarshot -n radarr --ignore-not-found && log "PVC deleted"
+    kubectl get pvc radarr-pvc-tarshot -n radarr &> /dev/null
+    if [ $? -eq 0 ]; then
+      log "Deleting PVC"
+      kubectl delete pvc radarr-pvc-tarshot -n radarr --ignore-not-found && log "PVC deleted"
+    else
+      log "PVC radarr-pvc-tarshot not found"
+    fi
 
     log "Assets cleaned up"
