[WIP] qBittorrent

diff --git a/qbittorrent/base/configmap.yaml b/qbittorrent/base/configmap.yaml
--- a/qbittorrent/base/configmap.yaml
+++ b/qbittorrent/base/configmap.yaml
@@ -21,77 +21,40 @@ data:
     git clone https://github.com/nodadyoushutup/kubernetes.git /tmp/git
     ./tmp/git/script/tarshot-copy.sh
   qBittorrent.conf: |
-    [Application]
-    FileLogger\Age=1
-    FileLogger\AgeType=1
-    FileLogger\Backup=true
-    FileLogger\DeleteOld=true
-    FileLogger\Enabled=true
-    FileLogger\MaxSizeBytes=66560
-    FileLogger\Path=/config/qBittorrent/logs
-    MemoryWorkingSetLimit=16384
-
-    [BitTorrent]
-    Session\AddExtensionToIncompleteFiles=true
-    Session\AlternativeGlobalDLSpeedLimit=51920
-    Session\AlternativeGlobalUPSpeedLimit=1024
-    Session\BandwidthSchedulerEnabled=false
-    Session\CheckingMemUsageSize=4096
-    Session\DHTEnabled=false
-    Session\DefaultSavePath=/media/storage
-    Session\ExcludedFileNames=
-    Session\FinishedTorrentExportDirectory=/torrents
-    Session\GlobalDLSpeedLimit=51920
-    Session\GlobalUPSpeedLimit=1024
-    Session\IgnoreSlowTorrentsForQueueing=true
-    Session\MaxActiveCheckingTorrents=1
-    Session\MaxActiveDownloads=15
-    Session\MaxActiveTorrents=100000
-    Session\MaxActiveUploads=100000
-    Session\MaxConcurrentHTTPAnnounces=300
-    Session\MaxConnections=200
-    Session\MaxConnectionsPerTorrent=-1
-    Session\MaxUploads=10
-    Session\MaxUploadsPerTorrent=-1
-    Session\PeXEnabled=false
-    Session\Port=10096
-    Session\QueueingSystemEnabled=true
-    Session\ResumeDataStorageType=SQLite
-    Session\SaveResumeDataInterval=15
-    Session\SlowTorrentsDownloadRate=100
-    Session\SlowTorrentsUploadRate=1
-    Session\Tags=issue, orphan
-    Session\TempPath=/downloads/temp
-    Session\TorrentStopCondition=None
-    Session\UseAlternativeGlobalSpeedLimit=true
-
-    [Core]
-    AutoDeleteAddedTorrentFile=Never
+    [AutoRun]
+    enabled=false
+    program=
 
     [LegalNotice]
     Accepted=true
 
-    [Meta]
-    MigrationVersion=6
-
-    [Network]
-    PortForwardingEnabled=false
-    Proxy\HostnameLookupEnabled=false
-    Proxy\Profiles\BitTorrent=true
-    Proxy\Profiles\Misc=true
-    Proxy\Profiles\RSS=true
-
     [Preferences]
-    General\Locale=en
-    MailNotification\req_auth=true
-    Scheduler\end_time=@Variant(\0\0\0\xf\0\xdb\xba\0)
-    Scheduler\start_time=@Variant(\0\0\0\xf\x4\xb8\x7f\0)
+    Connection\UPnP=false
+    Connection\PortRangeMin=6881
+    Downloads\SavePath=/downloads/
+    Downloads\ScanDirsV2=@Variant(\0\0\0\x1c\0\0\0\0)
+    Downloads\TempPath=/downloads/incomplete/
+    WebUI\Address=*
+    WebUI\ServerDomains=*
     WebUI\HostHeaderValidation=false
-    WebUI\LocalHostAuth=false
-    WebUI\Password_PBKDF2="@ByteArray(ufqyy/yMlwXhkVu+pnL63w==:ZFrtf8DNt/qzrAZV9QfXiKtu4e6CzakU2fBwtaeFQPTdlIzJx9JMFcHVNbNtym735JSQpyDd/JtYerwIZ0xIeg==)"
-    WebUI\Port=8080
-    WebUI\UseUPnP=false
+  init-config.conf: | 
+    #!/bin/sh
+    set -e
+    SOURCE_FILE="/script/qBittorrent.conf"
+    DEST_FILE="/config/qBittorrent/qBittorrent.conf"
 
-    [RSS]
-    AutoDownloader\DownloadRepacks=true
-    AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
+    # Check if the destination configuration file exists
+    if [ ! -f "$DEST_FILE" ]; then
+        echo "Configuration file not found at $DEST_FILE."
+        echo "Copying default configuration from $SOURCE_FILE to $DEST_FILE."
+
+        # Ensure the destination directory exists
+        mkdir -p $(dirname "$DEST_FILE")
+
+        # Copy the default configuration file to the destination
+        cp "$SOURCE_FILE" "$DEST_FILE"
+
+        echo "Default configuration copied."
+    else
+        echo "Configuration file already exists at $DEST_FILE. No action needed."
+    fi
